app:
  ui-path: /ui

tesler:
  bean:
    multipart-resolver:
      enabled: false
  meta:
    dev-panel-enabled: ${DEV_PANEL_ENABLED:true}
    directory: ${META_DIRECTORY:file:./src/main/resources/meta}
    view-allowed-roles-enabled: true
  widget:
    fields:
      include-packages: io.tesler.core.ui.model.json.field.subtypes, io.demo.conf.tesler.meta
  api:
    path: /api/v1
    use-servlet-context-path: false
  ui:
    path: /ui
    use-servlet-context-path: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
  datasource:
    name: primaryDS
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    drop-first: true
    change-log: classpath:/db/db.changelog-master.xml
  cache:
    type: None
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
    hibernate:
      naming:
        physical-strategy: io.tesler.model.core.hbn.ImprovedPhysicalNamingStrategy
  main:
    allow-bean-definition-overriding: true
    banner-mode: off

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:9080/auth}
  realm: jhipster
  resource: web_app
  bearer-only: true
  public-client: true
  use-resource-role-mappings: false
springdoc:
  packages-to-scan: io.demo

minio:
  access:
    name: 4eb6a7db8b58994ea61b
    secret: prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW
  url: http://localhost:9000
  bucket:
    name: edcs3gnsadevb